genomeDir: "/home/shared/hg_align_db/GRCm39_gencode_primary/star_index_ercc_phix"
gtfFile: "/home/shared/hg_align_db/GRCm39_gencode_primary/gencode.vM27.primary_assembly.annotation.ercc.phix.gtf"
bedFile: "~/@patrick/parsebio/mm10_RefSeq.bed"
